export const DISPOSABLE_DOMAINS = [
    "10minutemail.com",
    "10minutemail.net",
    "guerrillamail.com",
    "guerrillamailblock.com",
    "sharklasers.com",
    "grr.la",
    "guerrillamail.biz",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "yopmail.com",
    "temp-mail.org",
    "temp-mail.io",
    "tempmail.net",
    "tempmail.com",
    "mailinator.com",
    "trashmail.com",
    "maildrop.cc",
    "getnada.com",
    "dispostable.com",
    "throwawaymail.com",
    "burnermail.io",
    "fake-mail.com",
    "example.com",
    "test.com",
    // Generic PT-BR testing domains
    "teste.com",
    "teste.com.br",
    "exemplo.com",
    "exemplo.com.br",
    "123teste.com",
    "meuemail.com",
    "email.com",
    "usuario.com",
    // Add more as needed
] as const
